# Generated by Django 5.2.6 on 2025-09-15 09:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='balance_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Балансовая стоимость'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='status_doc',
            field=models.CharField(choices=[('active', 'Действующий'), ('to_written_off', 'К списанию'), ('written_off', 'Списан')], default='active', max_length=20, verbose_name='Статус по документам'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='status_real',
            field=models.CharField(choices=[('active', 'Действующий'), ('to_written_off', 'К списанию'), ('written_off', 'Списан')], default='active', max_length=20, verbose_name='Фактический статус'),
        ),
        migrations.AlterField(
            model_name='mac',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mac_address', to='inventory.inventory', verbose_name='Инвентарь'),
        ),
        migrations.AlterField(
            model_name='mac',
            name='ip_addresses',
            field=models.ManyToManyField(blank=True, related_name='mac_address', to='inventory.ip', verbose_name='IP-адреса'),
        ),
    ]
