# Generated by Django 5.2.6 on 2025-09-15 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_balance_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='inventory.models', verbose_name='Модель оборудования'),
        ),
    ]
