# Generated by Django 5.2.6 on 2025-09-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_model'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='responsible',
            constraint=models.UniqueConstraint(fields=('surname', 'name', 'patronymic'), name='unique_responsible'),
        ),
    ]
