# Generated by Django 5.2.6 on 2025-09-26 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_responsible_unique_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='inventory', through='inventory.InventoryAttribute', through_fields=('inventory', 'attribute'), to='inventory.attribute', verbose_name='Дополнительные атрибуты'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='current_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory', to='inventory.responsible', verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='inventory.models', verbose_name='Модель оборудования'),
        ),
        migrations.AlterField(
            model_name='models',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='models/', verbose_name='Изображение'),
        ),
    ]
